DROP TABLE IF EXISTS CAAS_TROPO_APP;
CREATE TABLE CAAS_TROPO_APP (
    APP_KEY VARCHAR(64),
    APP_TYPE VARCHAR(64),
    APP_STATUS VARCHAR(32),
    TROPO_MODE INTEGER,
    TROPO_TYPE INTEGER,
    TROPO_TEST_APP_ID INTEGER,
    TROPO_PROD_APP_ID INTEGER,
    TROPO_TEST_TOKEN VARCHAR(128),
    TROPO_PROD_TOKEN VARCHAR(128),
    TROPO_TEST_VOICE_URL VARCHAR(256),
    TROPO_PROD_VOICE_URL VARCHAR(256),
    TROPO_TEST_MESSAGE_URL VARCHAR(256),
    TROPO_PROD_MESSAGE_URL VARCHAR(256)
);

DROP TABLE IF EXISTS CAAS_TROPO_NUMBER;
CREATE TABLE CAAS_TROPO_NUMBER (
    RULE_NAME VARCHAR(64),
    START_NUMBER VARCHAR(64),
    END_NUMBER VARCHAR(64),
    REALM VARCHAR(64),
    PRIMARY KEY (RULE_NAME )
);

DROP TABLE IF EXISTS CASS_TROPO_AUTHZ_LOGIN;
CREATE TABLE CASS_TROPO_AUTHZ_LOGIN (
    AUTHZ_USER VARCHAR(64),
    TICKET VARCHAR(128),
    TIME_CREATED TIMESTAMP,
    VALIDITY_PERIOD BIGINT
);

DROP TABLE IF EXISTS CASS_TROPO_AUTHZ_CODE;
CREATE TABLE CASS_TROPO_AUTHZ_CODE (
    AUTHORIZATION_CODE  VARCHAR(64),
    TICKET VARCHAR(128),
    TIME_CREATED TIMESTAMP,
    VALIDITY_PERIOD BIGINT,
    PRIMARY KEY (AUTHORIZATION_CODE)
);

DROP TABLE IF EXISTS CASS_TROPO_ACCESS_TOKEN;
CREATE TABLE CASS_TROPO_ACCESS_TOKEN (
    ACCESS_TOKEN VARCHAR(64),
    TICKET VARCHAR(128),
    TIME_CREATED TIMESTAMP,
    VALIDITY_PERIOD BIGINT,
    TOKEN_SCOPE VARCHAR(64),
    TOKEN_STATE VARCHAR(64),
    PRIMARY KEY (ACCESS_TOKEN)
);

commit;
