#!/bin/bash

JOB_DIR=/var/paas/jobs/nginx
RUN_DIR=/var/paas/sys/run/nginx
LOG_DIR=/var/paas/sys/log/nginx
PIDFILE=$RUN_DIR/nginx.pid
PIDFILE1=$RUN_DIR/nginx_server.pid
LOG_FILE=$LOG_DIR/nginx.log
MONIT_CTL_LOG_FILE=${LOG_DIR}/nginx_ctl.log
case $1 in

  start)
    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    chmod -R 750 ${RUN_DIR}
    chmod -R 750 ${LOG_DIR}
    echo `date "+%F %T"` `whoami` "starting nginx..." >> ${MONIT_CTL_LOG_FILE}
    bash /var/paas/jobs/nginx/nginx_server restart
    cp $PIDFILE $PIDFILE1
    chmod 640 ${PIDFILE1}
    chmod 640 ${PIDFILE}

    chmod 640 ${MONIT_CTL_LOG_FILE}
    ;;

  stop)
    echo `date "+%F %T"` `whoami` "stopping nginx..." >> ${MONIT_CTL_LOG_FILE}
    /var/paas/jobs/nginx/nginx_server stop
    pid=`cat $PIDFILE1`
    kill $pid
    rm -f $PIDFILE1
    ;;

  *)
    echo "Usage: nginx_ctl {start|stop}"
    ;;
esac
