-- create procedure dustman to clear tables
CREATE OR REPLACE PROCEDURE dustman
IS
BEGIN
	-- clear table CASS_TROPO_AUTHZ_LOGIN
	DELETE FROM CASS_TROPO_AUTHZ_LOGIN WHERE EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) - EXTRACT(EPOCH FROM TIME_CREATED) > VALIDITY_PERIOD / 1000 + 1;
	
	-- clear table CASS_TROPO_AUTHZ_CODE
	DELETE FROM CASS_TROPO_AUTHZ_CODE  WHERE EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) - EXTRACT(EPOCH FROM TIME_CREATED) > VALIDITY_PERIOD / 1000 + 1;
	
	-- clear table CASS_TROPO_ACCESS_TOKEN
	DELETE FROM CASS_TROPO_ACCESS_TOKEN WHERE CURRENT_TIMESTAMP - TIME_CREATED > interval '24 hour';
	
	-- clear table IDN_OAUTH2_ACCESS_TOKEN
	DELETE FROM IDN_OAUTH2_ACCESS_TOKEN WHERE CURRENT_TIMESTAMP - TIME_CREATED > interval '24 hour';
	
	-- clear table AM_INVOKE_STATISTICS
	DELETE FROM AM_INVOKE_STATISTICS WHERE CURRENT_TIMESTAMP - TIME_CREATED > interval '30 day';
END;
/

-- create dbms job for execute dustman each hour  
call dbms_job.submit(10000, 'call dustman();', sysdate, 'sysdate+1/24');
